### ISSUE TITLE
数据预处理

### ISSUE THREAD

**Issue by ShangYuming** [ShomyLiu/pytorch-relation-extraction#19]
作者您好，我注意到FilterNYT.py中，130行
`epos = map(lambda x: int(x) + 1, sent[0:2])`
这部分，句子每一行的前两个已经是实体在句子中的index了，为什么要给他们+1呢？
谢谢，祝好

**Comment by ShomyLiu** [comment]
手动添加了blank放到了第0位。 所以其他需要向后移 在2018年12月28日 09:39，尚yu。 写道： 作者您好，我注意到FilterNYT.py中，130行 epos = map(lambda x: int(x) + 1, sent[0:2]) 这部分，句子每一行的前两个已经是实体在句子中的index了，为什么要给他们+1呢？ 谢谢，祝好 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
